/*
 * This source file was generated by the Gradle 'init' task
 */
package clinicproject;

public class App {

    public static void main(String[] args) {

        // Run application wtih GUI

    }
}
