version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
